### ISSUE TITLE
How do I use gwd/prepare_pseudo.py?

### ISSUE THREAD

**Issue by Keiku** [amirassov/kaggle-global-wheat-detection#3]
Thank you for publishing an elegant and detailed solution. I'm studying this now. By the way, how do I use `gwd/prepare_pseudo.py` ? When I use it as documented, I get the following error:

```
root@efac3ffa390a:/global-wheat-detection# python gwd/prepare_pseudo.py
Traceback (most recent call last):
  File "gwd/prepare_pseudo.py", line 31, in <module>
    main()
  File "gwd/prepare_pseudo.py", line 22, in main
    cfg.data.test.ann_file = cfg.data.test.ann_file.format(fold=args.fold)
AttributeError: 'Namespace' object has no attribute 'fold'
root@efac3ffa390a:/global-wheat-detection#
```

The dataset is as follows.

```
-rw-rw-r-- 1 keiichi.kuroyanagi keiichi.kuroyanagi  266  5月  4  2020 sample_submission.csv
-rw-rw-r-- 1 keiichi.kuroyanagi keiichi.kuroyanagi 8.0M  5月  4  2020 train.csv
-rw-rw-r-- 1 keiichi.kuroyanagi keiichi.kuroyanagi 608M 12月  5 21:43 global-wheat-detection.zip
drwxrwxr-x 2 keiichi.kuroyanagi keiichi.kuroyanagi 4.0K 12月  5 21:45 test/
drwxrwxr-x 2 keiichi.kuroyanagi keiichi.kuroyanagi 132K 12月  5 21:45 train/
drwxrwxr-x 4 keiichi.kuroyanagi keiichi.kuroyanagi 4.0K 12月 10 18:22 ../
drwxr-xr-x 2 root               root               4.0K 12月 10 19:39 distances/
drwxr-xr-x 2 root               root                68K 12月 10 19:55 mosaics/
-rw-r--r-- 1 root               root               159K 12月 10 19:55 mosaics.json
-rw-r--r-- 1 root               root                12M 12月 10 19:57 train_mosaic.csv
drwxr-xr-x 7 root               root               4.0K 12月 10 20:12 folds_v2/
drwxr-xr-x 2 root               root               240K 12月 10 20:28 crops_fold0/
-rw-r--r-- 1 root               root               306K 12月 10 20:28 coco_crops_fold0.json
drwxrwxr-x 8 keiichi.kuroyanagi keiichi.kuroyanagi 4.0K 12月 10 21:24 ./
-rw-r--r-- 1 root               root               2.9M 12月 10 21:24 crops_fold0_predictions.pkl
```

**Comment by amirassov** [comment]
Hello, @Keiku. It was a bug. I have fixed: https://github.com/amirassov/kaggle-global-wheat-detection/commit/914226a449bda5c82c033d8643fc7030312dc1b0
